### ISSUE TITLE
Not working (incompatibility?)

### ISSUE THREAD

**Issue by Yankshuru** [lyne408/smile-to-camera-se#1]
For some reason I can't make this work, there's some known incompatibility?

My load order, if helps:

https://pastebin.com/LN0zvT1C

**Comment by lyne408** [comment]
**Try to disable others head tracking or camera mods.**
----
[Smile to Camera] use API `SetLookAt()` and `SetHeadTracking()` which control the head node of player.
Many camera relative or head tracking relative mods use those APIs. 
Example: 
**Immersive First Person View-22306-9** makes [Smile to Camera] work incorrectly.

**Comment by Yankshuru** [comment]
> ## **Try to disable others head tracking or camera mods.**
> [Smile to Camera] use API `SetLookAt()` and `SetHeadTracking()` which control the head node of player.
> Many camera relative or head tracking relative mods use those APIs.
> Example:
> **Immersive First Person View-22306-9** makes [Smile to Camera] work incorrectly.

Solved by disabling Immersive First Person View head tracking on ini config file.

Thanks!
